### PR TITLE
Adjusted the where value in toolGetMapping()

### PR DESCRIPTION
**Pull request by whitehacker**
Went through all warnings displayed by `reposearch toolGetMapping` in `mrcommons` and fixed all the instances of `toolGetMapping` with missing `where`.

### CODE REVIEW

**Comment by LaviniaBaumstark** [comment]
did you check that there are no linter warnings?

**Comment by whitehacker** [comment]
> did you check that there are no linter warnings?

Yes, and fixed them.

**Comment by fbenke-pik** [comment]
Did you assume that all the mappings are in the mapping folder, or did you check one by one where the mapping is taken from and set the `where` argument accordingly?

**Comment by whitehacker** [comment]
> Did you assume that all the mappings are in the mapping folder, or did you check one by one where the mapping is taken from and set the `where` argument accordingly?

As I understood, `mappingfolder` points to `/p/projects/rd3mod/inputdata/mappings` and I went through all `toolGetMapping` instances and they use either type `regional` or  `sectoral` and they exist in `/p/projects/rd3mod/inputdata/mappings`. I didn't check `toolGetMapping` instances where the `where` is already set to `mrcommons` and didn't replace with `mappingfolder`

**Review by fbenke-pik — APPROVED** [review]

**Review by LaviniaBaumstark — APPROVED** [review]

**Pull request merged**
