### PR TITLE
Fill in missing Eurostat pop data with WB growth rates

### PR DESCRIPTION
**Pull request by johanneskoch94**

### CODE REVIEW

**Comment by johanneskoch94** [comment]
See https://github.com/pik-piam/mrremind/issues/108

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Nope.
```
> source("~/.active-rstudio-document", echo=TRUE)

> library(mrcommons)
Loading required package: magclass
Loading required package: madrat
Loading required package: mstools

> library(tidyverse)
── Attaching packages ───────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✓ ggplot2 3.3.5     ✓ purrr   0.3.4
✓ tibble  3.1.4     ✓ dplyr   1.0.7
✓ tidyr   1.1.3     ✓ stringr 1.4.0
✓ readr   2.0.1     ✓ forcats 0.5.1
── Conflicts ──────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()

> print(mrcommons:::calcPopulationPastEurostatWDI)
function(complete) {
  data_eurostat <- readSource("Eurostat", "population") / 1e+6
  data_wdi <- readSource("WDI", "SP.POP.TOTL")

  # Get EUR countries. 
  EUR_countries <- toolGetMapping("regionmappingH12.csv") %>% 
    tibble::as_tibble() %>% 
    filter(.data$RegionCode == "EUR") %>% 
    dplyr::pull(.data$CountryCode)
  
  # Fill in missing ( == 0) eurostat data using wdi growth rates 
  for (c in EUR_countries) {
    if (any(data_eurostat[c,,] == 0) && !all(data_eurostat[c,,] == 0)) {
       data_eurostat[c,,] <- harmonizeFutureGrPast(
         past = data_wdi[c,,], 
         future = data_eurostat[c, data_eurostat[c,,] != 0, ]
        )
    }
  }


  # Use WDI data for everything but the EUR_countries. Use Eurostat stat for those.
  data <- data_wdi
  data[EUR_countries,,] <- data_eurostat[EUR_countries,,]

  if (complete) {
    fill <- readSource("MissingIslands", subtype = "pop", convert = FALSE)
    data <- completeData(data, fill)
  }

  data
}
<bytecode: 0x5636688708c0>
<environment: namespace:mrcommons>

> calcOutput('Population', aggregate = FALSE, FiveYearSteps = FALSE) %>% 
+   `[`('FRA',,'SSP2', pmatch = TRUE) %>% 
+   as.data.frame() %>% 
+   filt .... [TRUNCATED] 

Run calcOutput(type = "Population", aggregate = FALSE, FiveYearSteps = FALSE)
~ WARNING: Mapping in mrcommons:::calcEmissionInventory not found!
~  - loading cache calcPopulation-F04e78c6a-aa608a57.rds
Exit calcOutput(type = "Population", aggregate = FALSE, FiveYearSteps = FALSE) in 2.21 seconds
# A tibble: 31 × 5
    Cell Region Year  pop_SSP2 pop_SSP2Ariadne
   <int> <chr>  <fct>    <dbl>           <dbl>
 1    NA FRA    1960      46.6            55.8
 2    NA FRA    1961      47.2            55.8
 3    NA FRA    1962      47.9            55.8
 4    NA FRA    1963      48.6            55.8
 5    NA FRA    1964      49.2            55.8
 6    NA FRA    1965      49.8            55.8
 7    NA FRA    1966      50.3            55.8
 8    NA FRA    1967      50.8            55.8
 9    NA FRA    1968      51.2            55.8
10    NA FRA    1969      51.6            55.8
11    NA FRA    1970      52.0            55.8
12    NA FRA    1971      52.4            55.8
13    NA FRA    1972      52.8            55.8
14    NA FRA    1973      53.2            55.8
15    NA FRA    1974      53.6            55.8
16    NA FRA    1975      53.9            55.8
17    NA FRA    1976      54.2            55.8
18    NA FRA    1977      54.5            55.8
19    NA FRA    1978      54.7            55.8
20    NA FRA    1979      54.9            55.8
21    NA FRA    1980      55.2            55.8
22    NA FRA    1981      55.4            55.8
23    NA FRA    1982      55.7            55.8
24    NA FRA    1983      56.0            56.0
25    NA FRA    1984      56.3            56.3
26    NA FRA    1985      56.7            56.6
27    NA FRA    1986      57.0            56.9
28    NA FRA    1987      57.3            57.2
29    NA FRA    1988      57.6            57.5
30    NA FRA    1989      57.9            57.9
31    NA FRA    1990      58.2            58.2
Warning message:
Mapping in mrcommons:::calcEmissionInventory not found! 
```
Maybe write a test to check for sensible historic values first :bulb:

**Review by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q — CHANGES_REQUESTED** [review]
This does not change the returned figures.

**Comment by johanneskoch94** [comment]
I don't know what your setup is but could it be that you loaded a bad cache? You can look in /p/tmp/jokoch/eurostat_pr_test. New library, new cache, looks good. Check the renv.lock file for package versions; mrcommons is installed from this branch.

pop

**Comment by johanneskoch94** [comment]
Ah I know, I did forget to run lucode2::buildlibrary().. maybe that confused your setup? I'll push a fix for that now.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Indeed, manually ignoring the cache produces proper results.

But that [shouldn't have been necessary](https://github.com/pik-piam/madrat/blob/2a321caad22c2b9b472d38073bc664ae2991571f/vignettes/madrat-caching.Rmd#L32):
> In order to estimate whether a calculation should be rerun or whether the data can be read from cache madrat creates fingerprints for each function. If the fingerprint of the current function call agrees with the fingerprint of the corresponding cache file the cache is assumed up-to-date and read in.

Once more, one shouldn't rely on `madbrat`.

**Review by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q — APPROVED** [review]

**Pull request merged**
