### PR TITLE
move structuremappingPE and structuremappingIO_outputs to package

### LINKED ISSUE #97: move structuremappingPE to package

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
close #97 

Note: This introduces an implied dependency on the `mrremind` package, where the `structuremappingIO_outputs.csv` file has been moved.  This will only be a problem if somebody where to use the `mredgebuildings` package without having the `mrremind` package installed.  Is that likely/desired, @robinhasse?

```
> getDependencies('calcIOEdgeBuildings', 'dout') %>% arrange(package, type)
               func type         package                                call     hash
1      calcShareETP calc mredgebuildings      mredgebuildings:::calcShareETP 7304e9b8
2  calcShareOdyssee calc mredgebuildings  mredgebuildings:::calcShareOdyssee 97d3b44e
3        calcShares calc mredgebuildings        mredgebuildings:::calcShares 4d398301
4 fullEDGEBUILDINGS full mredgebuildings mredgebuildings:::fullEDGEBUILDINGS 3fc07d8e
5      calcFEShares calc        mrremind             mrremind:::calcFEShares a4b6be9a
6            calcIO calc        mrremind                   mrremind:::calcIO d70068c3
7          readEDGE read        mrremind                 mrremind:::readEDGE e1edbf9b
```

### CODE REVIEW

**Comment by fbenke-pik** [comment]
Tricky. 
As mrremind is not listed as an explicit dependency, it also won't be installed when installing mrcommons, right? Hence, also no way of enforcing a minimal version of mrremind.
On the other hand side, if it were listed as an explicit dependency, we would have a problem with circular dependencies...

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Well, we would need to move `structuremappingIO_outputs.csv` to `mrcommons`.  But that would mean commits in two packages while sorting out the mappings.
Robin's call.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@robinhasse bump.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@robinhasse bump.

**Comment by robinhasse** [comment]
So sorry for the long delay. I would like to move it to mrcommons. We actually don't want mrremind to be a dependency of mredgebuildings. To my understanding, that's what we have mrcommons for.

**Review by fbenke-pik — APPROVED** [review]
Fine by me, but in the end should only be merged with Robin's approval.

**Pull request merged**
